sudo: required
services: 
  - docker

before_install:
  - docker build -t jiayu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jiayu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-171649763315"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



#/FT7H36K252/pDuTug2WosIrgN/YXhQLg0pbiqOx